version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    sabrina_test:
      image: deephdc/deep-oc-sabrina_test
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    sabrina_test-gpu:
      image: deephdc/deep-oc-sabrina_test:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    sabrina_test-rclone:
      extends:
        service: sabrina_test
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
